version: '3.8'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    command: >
      --api-id=${TELEGRAM_API_ID}
      --api-hash=${TELEGRAM_API_HASH}
      --local
      --verbosity=1
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  telegram-drive-bot:
    build: .
    container_name: telegram-drive-bot
    restart: unless-stopped
    depends_on:
      - telegram-bot-api
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GOOGLE_CREDENTIALS_FILE=credentials.json
      - BOT_API_SERVER=http://telegram-bot-api:8081
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  telegram-bot-api-data:
    driver: local

