version: '3.8'

services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    ports:
      - "8081:8081"
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_LOCAL=true
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  telegram-drive-bot:
    build: .
    depends_on:
      - telegram-bot-api
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GOOGLE_CREDENTIALS_FILE=credentials.json
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - OWNER_ID=${OWNER_ID}
      - BOT_API_SERVER=http://telegram-bot-api:8081
    volumes:
      - ./credentials.json:/app/credentials.json:ro

volumes:
  telegram-bot-api-data:
    driver: local